// Core/PrivacyFilter.swift
import AppKit

enum PrivacyFilter {
    /// nspasteboard.org 约定的标记：密码管理器等会给敏感/瞬态内容打上这些类型
    private static let blockedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// 返回 true 表示这次剪贴板内容应当被完全忽略
    static func shouldIgnore(_ pb: NSPasteboard, excludedBundleIDs: Set<String>) -> Bool {
        guard let types = pb.types, !types.isEmpty else { return true }
        if types.contains(where: { blockedTypes.contains($0.rawValue) }) { return true }
        if let bid = NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
           excludedBundleIDs.contains(bid) {
            return true
        }
        return false
    }
}
